### ISSUE TITLE
NyaaCore not load. Spigot 1.12.2

### ISSUE THREAD

**Issue by GluGluGlu** [NyaaCat/NyaaCore#24]
[05:45:09 INFO]: This server is running CraftBukkit version git-Spigot-549c1fa-45c8386 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)
[05:45:09 INFO]: Server Ping Player Sample Count: 12
[05:45:09 INFO]: Using 4 threads for Netty based IO
[05:45:09 INFO]: Debug logging is disabled
[05:45:09 INFO]: Generating keypair
[05:45:10 INFO]: Starting Minecraft server on *:25565
[05:45:10 INFO]: Using epoll channel type
[05:45:10 INFO]: Set PluginClassLoader as parallel capable
[05:45:10 ERROR]: Could not load 'plugins/NyaaCore-v4.1.71-mc1.12.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: LangUtils
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:216) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:306) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-549c1fa-45c8386]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by phoenixlzx** [comment]
Install langutils

https://github.com/MascusJeoraly/LanguageUtils/releases/download/1.9/LangUtils-1.9.jar
