### ISSUE TITLE
您好，在使用时该插件报错了

### ISSUE THREAD

**Issue by NTDLX** [NyaaCat/NyaaCore#25]
Could not load 'plugins\NyaaCore-v4.1.71-mc1.12.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: Vault
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:216) [spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:306) [spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:205) [spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:545) [spigot-1.12.2.jar:git-Spigot-549c1fa-8c37e2e]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_152]

请问这种情况怎么解决，感谢您的回复！

**Comment by cyilin** [comment]
需要安装Vault和LangUtils。
https://www.spigotmc.org/resources/1-7-x-1-12-language-utils.8859/
https://dev.bukkit.org/projects/vault
